# Generated by Django 4.1.7 on 2023-07-20 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=400)),
                ('dob', models.DateField()),
                ('age', models.IntegerField()),
                ('preferred_dance_style', models.CharField(max_length=50)),
                ('experience_level', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Beginner', max_length=50)),
                ('preferred_class_time', models.CharField(max_length=100)),
                ('emergency_contact', models.CharField(max_length=12)),
            ],
        ),
    ]
