# Generated by Django 4.1.7 on 2023-07-20 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dance', '0002_rename_applications_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='photo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
