# Generated by Django 4.1.7 on 2023-08-20 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_style_remove_profile_style_profile_style'),
        ('Dance', '0003_application_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(max_length=50)),
                ('media_type', models.IntegerField()),
                ('shortcode', models.CharField(max_length=50)),
                ('thumbnail', models.URLField()),
                ('comments', models.IntegerField()),
                ('likes', models.IntegerField()),
                ('views', models.IntegerField()),
                ('video_url', models.URLField()),
                ('user', models.ManyToManyField(blank=True, to='accounts.profile')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
    ]
