# Generated by Django 4.1.7 on 2023-08-20 19:05

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0008_style_remove_profile_style_profile_style'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workshops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('date', models.DateField(default=datetime.datetime(2023, 8, 21, 0, 35, 38, 369787))),
                ('description', models.TextField()),
                ('duration', models.CharField(max_length=20)),
                ('location_url', models.URLField()),
                ('cover_image', models.URLField()),
                ('premium', models.BooleanField(default=False)),
                ('original_price', models.IntegerField(blank=True)),
                ('offer_price', models.IntegerField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('dance_instructor', models.ManyToManyField(to='accounts.profile', verbose_name='dance_instructors')),
                ('dance_style', models.ManyToManyField(to='accounts.style')),
            ],
        ),
    ]
