# Generated by Django 4.1.7 on 2023-08-20 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0002_workshop_delete_workshops'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
