# Generated by Django 4.1.7 on 2023-03-08 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='role',
        ),
        migrations.AlterField(
            model_name='profile',
            name='team',
            field=models.CharField(blank=True, choices=[('Ck6', 'ck6'), ('Kclan', 'kclan')], default='KalaNidhi', max_length=50),
        ),
    ]
