# Generated by Django 4.1.7 on 2023-06-26 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='style',
            field=models.CharField(choices=[('Dance', 'Dance'), ('Hiphop', 'Hiphop'), ('FreeStyle', 'FreeStyle'), ('Contemporary', 'Contemporary'), ('lock&pop', 'lock&pop')], default='Dance', max_length=50),
        ),
    ]
