# Generated by Django 4.1.7 on 2023-08-20 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_profile_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Style',
                'verbose_name_plural': 'Styles',
            },
        ),
        migrations.RemoveField(
            model_name='profile',
            name='style',
        ),
        migrations.AddField(
            model_name='profile',
            name='style',
            field=models.ManyToManyField(to='accounts.style'),
        ),
    ]
