# Generated by Django 4.1.7 on 2024-01-07 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_style_remove_profile_style_profile_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='style',
            field=models.ManyToManyField(blank=True, to='accounts.style'),
        ),
    ]
